import { MakeLogicType, afterMount, connect, kea, listeners, path, reducers } from 'kea'
import { forms } from 'kea-forms'
import type { DeepPartial, DeepPartialMap, FieldName, ValidationErrorType } from 'kea-forms'
import { loaders } from 'kea-loaders'
import posthog from 'posthog-js'

import { lemonToast } from '@posthog/lemon-ui'

import { projectLogic } from 'scenes/projectLogic'

import { cloudAgentsSettingsPartialUpdate, cloudAgentsSettingsRetrieve } from '../generated/api'
import type {
    CloudAgentSettingsApi,
    InferenceModeEnumApi,
    PatchedCloudAgentSettingsUpdateApi,
    SizeNameEnumApi,
} from '../generated/api.schemas'

export interface TeamDefaultsForm {
    repository: string
    branch: string
    model: string | null
    size: SizeNameEnumApi | null
    inference: InferenceModeEnumApi | null
    instructions: string
    default_profile: string | null
}

const EMPTY_TEAM_DEFAULTS: TeamDefaultsForm = {
    repository: '',
    branch: '',
    model: null,
    size: null,
    inference: null,
    instructions: '',
    default_profile: null,
}

function toForm(settings: CloudAgentSettingsApi): TeamDefaultsForm {
    return {
        repository: settings.repository ?? '',
        branch: settings.branch ?? '',
        model: settings.model ?? null,
        size: settings.size ?? null,
        inference: settings.inference ?? null,
        instructions: settings.instructions ?? '',
        default_profile: settings.default_profile,
    }
}

function toPatch(form: TeamDefaultsForm): PatchedCloudAgentSettingsUpdateApi {
    return {
        repository: form.repository.trim() || null,
        branch: form.branch.trim() || null,
        model: form.model,
        size: form.size,
        inference: form.inference,
        instructions: form.instructions.trim() || null,
        default_profile: form.default_profile,
    }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface cloudAgentsSettingsLogicValues {
    currentProjectId: number | null // projectLogic
    isTeamDefaultsSubmitting: boolean
    isTeamDefaultsValid: boolean
    settings: CloudAgentSettingsApi | null
    settingsLoadFailed: boolean
    settingsLoading: boolean
    showTeamDefaultsErrors: boolean
    teamDefaults: TeamDefaultsForm
    teamDefaultsAllErrors: Record<string, any>
    teamDefaultsChanged: boolean
    teamDefaultsErrors: DeepPartialMap<TeamDefaultsForm, ValidationErrorType>
    teamDefaultsHasErrors: boolean
    teamDefaultsManualErrors: Record<string, any>
    teamDefaultsTouched: boolean
    teamDefaultsTouches: Record<string, boolean>
    teamDefaultsValidationErrors: DeepPartialMap<TeamDefaultsForm, ValidationErrorType>
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface cloudAgentsSettingsLogicActions {
    loadSettings: () => any
    loadSettingsFailure: (
        error: string,
        errorObject?: any
    ) => {
        error: string
        errorObject?: any
    }
    loadSettingsSuccess: (
        settings: CloudAgentSettingsApi,
        payload?: any
    ) => {
        settings: CloudAgentSettingsApi
        payload?: any
    }
    resetTeamDefaults: (values?: TeamDefaultsForm) => {
        values?: TeamDefaultsForm
    }
    setTeamDefaultsManualErrors: (errors: Record<string, any>) => {
        errors: Record<string, any>
    }
    setTeamDefaultsValue: (
        key: FieldName,
        value: any
    ) => {
        name: FieldName
        value: any
    }
    setTeamDefaultsValues: (values: DeepPartial<TeamDefaultsForm>) => {
        values: DeepPartial<TeamDefaultsForm>
    }
    submitTeamDefaults: () => {
        value: boolean
    }
    submitTeamDefaultsFailure: (
        error: Error,
        errors: Record<string, any>
    ) => {
        error: Error
        errors: Record<string, any>
    }
    submitTeamDefaultsRequest: (teamDefaults: TeamDefaultsForm) => {
        teamDefaults: TeamDefaultsForm
    }
    submitTeamDefaultsSuccess: (teamDefaults: TeamDefaultsForm) => {
        teamDefaults: TeamDefaultsForm
    }
    touchTeamDefaultsField: (key: string) => {
        key: string
    }
}

export type cloudAgentsSettingsLogicType = MakeLogicType<
    cloudAgentsSettingsLogicValues,
    cloudAgentsSettingsLogicActions
>

export const cloudAgentsSettingsLogic = kea<cloudAgentsSettingsLogicType>([
    path(['products', 'cloud_agents', 'frontend', 'logics', 'cloudAgentsSettingsLogic']),
    connect(() => ({ values: [projectLogic, ['currentProjectId']] })),
    loaders(({ values }) => ({
        settings: [
            null as CloudAgentSettingsApi | null,
            {
                loadSettings: async (): Promise<CloudAgentSettingsApi> =>
                    await cloudAgentsSettingsRetrieve(String(values.currentProjectId)),
            },
        ],
    })),
    reducers({
        settingsLoadFailed: [false, { loadSettings: () => false, loadSettingsFailure: () => true }],
    }),
    forms(({ actions, values }) => ({
        teamDefaults: {
            defaults: EMPTY_TEAM_DEFAULTS,
            submit: async (form) => {
                try {
                    const settings = await cloudAgentsSettingsPartialUpdate(
                        String(values.currentProjectId),
                        toPatch(form)
                    )
                    actions.loadSettingsSuccess(settings)
                    // pinned: analytics event name. A rename breaks the dashboards that read it.
                    posthog.capture('cloud_agents_settings_saved')
                    lemonToast.success('Saved the team defaults')
                } catch (error) {
                    const detail = (error as { detail?: string | null }).detail
                    lemonToast.error(detail || 'Could not save the team defaults. Try again.')
                    throw error
                }
            },
        },
    })),
    listeners(({ actions }) => ({
        loadSettingsSuccess: ({ settings }) => {
            if (settings) {
                actions.resetTeamDefaults(toForm(settings))
            }
        },
    })),
    afterMount(({ actions }) => {
        actions.loadSettings()
    }),
])
