import { MakeLogicType, afterMount, connect, kea, key, listeners, path, props, reducers, selectors } from 'kea'
import { forms } from 'kea-forms'
import type { DeepPartial, DeepPartialMap, FieldName, ValidationErrorType } from 'kea-forms'
import { loaders } from 'kea-loaders'
import { router } from 'kea-router'
import posthog from 'posthog-js'

import { lemonToast } from '@posthog/lemon-ui'

import { projectLogic } from 'scenes/projectLogic'
import { urls } from 'scenes/urls'

import {
    cloudAgentsProfilesCreate,
    cloudAgentsProfilesPartialUpdate,
    cloudAgentsProfilesRetrieve,
} from '../generated/api'
import type { InferenceModeEnumApi, ProfileApi, ProfileCreateApi, SizeNameEnumApi } from '../generated/api.schemas'

export interface CloudAgentProfileLogicProps {
    /** The profile ID, or `new` for the create form. */
    id: string
}

export interface ProfileForm {
    name: string
    description: string
    repository: string
    branch: string
    model: string | null
    size: SizeNameEnumApi | null
    inference: InferenceModeEnumApi | null
    instructions: string
    tags: string[]
}

const EMPTY_PROFILE: ProfileForm = {
    name: '',
    description: '',
    repository: '',
    branch: '',
    model: null,
    size: null,
    inference: null,
    instructions: '',
    tags: [],
}

function toForm(profile: ProfileApi): ProfileForm {
    return {
        name: profile.name,
        description: profile.description,
        repository: profile.repository ?? '',
        branch: profile.branch ?? '',
        model: profile.model ?? null,
        size: profile.size ?? null,
        inference: profile.inference ?? null,
        instructions: profile.instructions ?? '',
        tags: profile.tags,
    }
}

function toRequest(form: ProfileForm): ProfileCreateApi {
    return {
        name: form.name.trim(),
        description: form.description.trim(),
        repository: form.repository.trim() || null,
        branch: form.branch.trim() || null,
        model: form.model,
        size: form.size,
        inference: form.inference,
        instructions: form.instructions.trim() || null,
        tags: form.tags,
    }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface cloudAgentProfileLogicValues {
    currentProjectId: number | null // projectLogic
    isNew: boolean
    isProfileFormSubmitting: boolean
    isProfileFormValid: boolean
    profile: ProfileApi | null
    profileForm: ProfileForm
    profileFormAllErrors: Record<string, any>
    profileFormChanged: boolean
    profileFormErrors: DeepPartialMap<ProfileForm, ValidationErrorType>
    profileFormHasErrors: boolean
    profileFormManualErrors: Record<string, any>
    profileFormTouched: boolean
    profileFormTouches: Record<string, boolean>
    profileFormValidationErrors: DeepPartialMap<ProfileForm, ValidationErrorType>
    profileLoadError: 'failed' | 'not_found' | null
    profileLoading: boolean
    showProfileFormErrors: boolean
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface cloudAgentProfileLogicActions {
    loadProfile: () => any
    loadProfileFailure: (
        error: string,
        errorObject?: any
    ) => {
        error: string
        errorObject?: any
    }
    loadProfileSuccess: (
        profile: ProfileApi,
        payload?: any
    ) => {
        profile: ProfileApi
        payload?: any
    }
    resetProfileForm: (values?: ProfileForm) => {
        values?: ProfileForm
    }
    setProfileFormManualErrors: (errors: Record<string, any>) => {
        errors: Record<string, any>
    }
    setProfileFormValue: (
        key: FieldName,
        value: any
    ) => {
        name: FieldName
        value: any
    }
    setProfileFormValues: (values: DeepPartial<ProfileForm>) => {
        values: DeepPartial<ProfileForm>
    }
    submitProfileForm: () => {
        value: boolean
    }
    submitProfileFormFailure: (
        error: Error,
        errors: Record<string, any>
    ) => {
        error: Error
        errors: Record<string, any>
    }
    submitProfileFormRequest: (profileForm: ProfileForm) => {
        profileForm: ProfileForm
    }
    submitProfileFormSuccess: (profileForm: ProfileForm) => {
        profileForm: ProfileForm
    }
    touchProfileFormField: (key: string) => {
        key: string
    }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface cloudAgentProfileLogicMeta {
    key: string
    __keaTypeGenInternalSelectorTypes: {
        isNew: (arg: any) => boolean
    }
}

export type cloudAgentProfileLogicType = MakeLogicType<
    cloudAgentProfileLogicValues,
    cloudAgentProfileLogicActions,
    CloudAgentProfileLogicProps,
    cloudAgentProfileLogicMeta
>

export const cloudAgentProfileLogic = kea<cloudAgentProfileLogicType>([
    props({} as CloudAgentProfileLogicProps),
    key((props) => props.id),
    path((key) => ['products', 'cloud_agents', 'frontend', 'logics', 'cloudAgentProfileLogic', key]),
    connect(() => ({ values: [projectLogic, ['currentProjectId']] })),
    loaders(({ props, values }) => ({
        profile: [
            null as ProfileApi | null,
            {
                loadProfile: async (): Promise<ProfileApi> =>
                    await cloudAgentsProfilesRetrieve(String(values.currentProjectId), props.id),
            },
        ],
    })),
    reducers({
        profileLoadError: [
            null as 'not_found' | 'failed' | null,
            {
                loadProfileSuccess: () => null,
                loadProfileFailure: (_, { errorObject }) => (errorObject?.status === 404 ? 'not_found' : 'failed'),
            },
        ],
    }),
    forms(({ actions, props, values }) => ({
        profileForm: {
            defaults: EMPTY_PROFILE,
            errors: ({ name, repository }) => ({
                name: !name.trim() ? 'Give the profile a name' : undefined,
                repository:
                    repository.trim() && !/^[\w.-]+\/[\w.-]+$/.test(repository.trim())
                        ? 'Use the form owner/name, for example acme/web'
                        : undefined,
            }),
            submit: async (form) => {
                const isNew = props.id === 'new'
                const projectId = String(values.currentProjectId)
                try {
                    if (isNew) {
                        await cloudAgentsProfilesCreate(projectId, toRequest(form))
                    } else {
                        await cloudAgentsProfilesPartialUpdate(projectId, props.id, toRequest(form))
                    }
                } catch (error) {
                    const { attr, detail } = error as { attr?: string | null; detail?: string | null }
                    if (attr && attr in form && detail) {
                        actions.setProfileFormManualErrors({ [attr]: detail })
                    } else {
                        lemonToast.error(detail || 'Could not save the profile. Try again.')
                    }
                    throw error
                }
                // pinned: analytics event and property names. A rename breaks the dashboards that read them.
                posthog.capture('cloud_agents_profile_saved', { is_new: isNew })
                lemonToast.success(`Saved the profile "${form.name.trim()}"`)
                router.actions.push(urls.cloudAgentProfiles())
            },
        },
    })),
    selectors({
        isNew: [() => [(_, props) => props.id], (id): boolean => id === 'new'],
    }),
    listeners(({ actions }) => ({
        loadProfileSuccess: ({ profile }) => {
            if (profile) {
                actions.resetProfileForm(toForm(profile))
            }
        },
    })),
    afterMount(({ actions, props }) => {
        if (props.id !== 'new') {
            actions.loadProfile()
        }
    }),
])
