import { MakeLogicType, actions, connect, kea, listeners, path, reducers, selectors } from 'kea'
import { forms } from 'kea-forms'
import type { DeepPartial, DeepPartialMap, FieldName, ValidationErrorType } from 'kea-forms'
import { router, urlToAction } from 'kea-router'
import posthog from 'posthog-js'

import { projectLogic } from 'scenes/projectLogic'
import { urls } from 'scenes/urls'

import { cloudAgentsRunsCreate } from '../generated/api'
import type {
    CloudAgentRunCreateApi,
    CloudAgentSettingsApi,
    CloudAgentSizeApi,
    InferenceModeEnumApi,
    ProfileApi,
    SizeNameEnumApi,
} from '../generated/api.schemas'
import type { CloudAgentRateCardApi } from '../generated/api.schemas'
import { describeRunError } from '../utils/errors'
import { cloudAgentProfilesLogic } from './cloudAgentProfilesLogic'
import { cloudAgentsCatalogLogic } from './cloudAgentsCatalogLogic'
import { cloudAgentsSettingsLogic } from './cloudAgentsSettingsLogic'

/** The search parameter that opens the modal, so "start a run" has a link. */
export const NEW_RUN_SEARCH_PARAM = 'new_run'

/** The length of the example in the cost line under the box size select. */
export const COST_EXAMPLE_MINUTES = 15

export interface NewRunForm {
    prompt: string
    repository: string
    branch: string
    profile: string | null
    model: string | null
    size: SizeNameEnumApi | null
    inference: InferenceModeEnumApi | null
}

type RunDefaults = Pick<ProfileApi | CloudAgentSettingsApi, 'repository' | 'branch' | 'model' | 'size' | 'inference'>

function prefill(defaults: RunDefaults | null, fallback: RunDefaults | null): Omit<NewRunForm, 'prompt' | 'profile'> {
    return {
        repository: defaults?.repository ?? fallback?.repository ?? '',
        branch: defaults?.branch ?? fallback?.branch ?? '',
        model: defaults?.model ?? fallback?.model ?? null,
        size: defaults?.size ?? fallback?.size ?? null,
        inference: defaults?.inference ?? fallback?.inference ?? null,
    }
}

function toRequest(form: NewRunForm): CloudAgentRunCreateApi {
    return {
        prompt: form.prompt.trim(),
        ...(form.repository.trim() ? { repository: form.repository.trim() } : {}),
        ...(form.branch.trim() ? { branch: form.branch.trim() } : {}),
        ...(form.profile ? { profile: form.profile } : {}),
        ...(form.model ? { model: form.model } : {}),
        ...(form.size ? { size: form.size } : {}),
        ...(form.inference ? { inference: form.inference } : {}),
    }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface cloudAgentsNewRunLogicValues {
    profiles: ProfileApi[] | null // cloudAgentProfilesLogic
    rates: CloudAgentRateCardApi | null // cloudAgentsCatalogLogic
    sizes: CloudAgentSizeApi[] // cloudAgentsCatalogLogic
    settings: CloudAgentSettingsApi | null // cloudAgentsSettingsLogic
    currentProjectId: number | null // projectLogic
    isNewRunModalOpen: boolean
    isNewRunSubmitting: boolean
    isNewRunValid: boolean
    newRun: NewRunForm
    newRunAllErrors: Record<string, any>
    newRunChanged: boolean
    newRunError: string | null
    newRunErrors: DeepPartialMap<NewRunForm, ValidationErrorType>
    newRunHasErrors: boolean
    newRunManualErrors: Record<string, any>
    newRunTouched: boolean
    newRunTouches: Record<string, boolean>
    newRunValidationErrors: DeepPartialMap<NewRunForm, ValidationErrorType>
    selectedProfile: ProfileApi | null
    selectedSize: CloudAgentSizeApi | null
    showNewRunErrors: boolean
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface cloudAgentsNewRunLogicActions {
    loadSettingsSuccess: (
        settings: CloudAgentSettingsApi,
        payload?: any
    ) => {
        payload?: any
        settings: CloudAgentSettingsApi
    } // cloudAgentsSettingsLogic
    closeNewRunModal: () => {
        value: true
    }
    openNewRunModal: () => {
        value: true
    }
    resetNewRun: (values?: NewRunForm) => {
        values?: NewRunForm
    }
    selectProfile: (profileId: string | null) => {
        profileId: string | null
    }
    setNewRunManualErrors: (errors: Record<string, any>) => {
        errors: Record<string, any>
    }
    setNewRunValue: (
        key: FieldName,
        value: any
    ) => {
        name: FieldName
        value: any
    }
    setNewRunValues: (values: DeepPartial<NewRunForm>) => {
        values: DeepPartial<NewRunForm>
    }
    submitNewRun: () => {
        value: boolean
    }
    submitNewRunFailure: (
        error: Error,
        errors: Record<string, any>
    ) => {
        error: Error
        errors: Record<string, any>
    }
    submitNewRunRequest: (newRun: NewRunForm) => {
        newRun: NewRunForm
    }
    submitNewRunSuccess: (newRun: NewRunForm) => {
        newRun: NewRunForm
    }
    touchNewRunField: (key: string) => {
        key: string
    }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface cloudAgentsNewRunLogicMeta {
    __keaTypeGenInternalSelectorTypes: {
        selectedProfile: (newRun: NewRunForm, profiles: ProfileApi[] | null) => ProfileApi | null
        selectedSize: (newRun: NewRunForm, sizes: CloudAgentSizeApi[]) => CloudAgentSizeApi | null
    }
}

export type cloudAgentsNewRunLogicType = MakeLogicType<
    cloudAgentsNewRunLogicValues,
    cloudAgentsNewRunLogicActions,
    Record<string, any>,
    cloudAgentsNewRunLogicMeta
>

export const cloudAgentsNewRunLogic = kea<cloudAgentsNewRunLogicType>([
    path(['products', 'cloud_agents', 'frontend', 'logics', 'cloudAgentsNewRunLogic']),
    connect(() => ({
        values: [
            projectLogic,
            ['currentProjectId'],
            cloudAgentsCatalogLogic,
            ['sizes', 'rates'],
            cloudAgentsSettingsLogic,
            ['settings'],
            cloudAgentProfilesLogic,
            ['profiles'],
        ],
        actions: [cloudAgentsSettingsLogic, ['loadSettingsSuccess']],
    })),
    actions({
        openNewRunModal: true,
        closeNewRunModal: true,
        selectProfile: (profileId: string | null) => ({ profileId }),
    }),
    reducers({
        isNewRunModalOpen: [false, { openNewRunModal: () => true, closeNewRunModal: () => false }],
        newRunError: [
            null as string | null,
            {
                openNewRunModal: () => null,
                submitNewRun: () => null,
                submitNewRunFailure: (_, { error }) =>
                    describeRunError(
                        error,
                        'Could not start the run. Try again, and contact support if it keeps happening.'
                    ),
            },
        ],
    }),
    forms(({ actions, values }) => ({
        newRun: {
            defaults: {
                prompt: '',
                repository: '',
                branch: '',
                profile: null,
                model: null,
                size: null,
                inference: null,
            } as NewRunForm,
            errors: ({ prompt, repository }) => ({
                prompt: !prompt.trim() ? 'Tell the agent what to do' : undefined,
                repository:
                    repository.trim() && !/^[\w.-]+\/[\w.-]+$/.test(repository.trim())
                        ? 'Use the form owner/name, for example acme/web'
                        : undefined,
            }),
            submit: async (form) => {
                const run = await cloudAgentsRunsCreate(String(values.currentProjectId), toRequest(form))
                // pinned: analytics event and property names. A rename breaks the dashboards that read them.
                posthog.capture('cloud_agents_run_submitted', {
                    size: run.config.size.name,
                    inference: run.config.inference,
                    has_profile: !!form.profile,
                })
                actions.closeNewRunModal()
                router.actions.push(urls.cloudAgentRun(run.id))
            },
        },
    })),
    selectors({
        selectedProfile: [
            (s) => [s.newRun, s.profiles],
            (newRun: NewRunForm, profiles: ProfileApi[] | null): ProfileApi | null =>
                profiles?.find((profile) => profile.name === newRun.profile) ?? null,
        ],
        selectedSize: [
            (s) => [s.newRun, s.sizes],
            (newRun: NewRunForm, sizes: CloudAgentSizeApi[]): CloudAgentSizeApi | null =>
                sizes.find((size) => size.name === newRun.size) ?? null,
        ],
    }),
    listeners(({ actions, values }) => ({
        openNewRunModal: () => {
            actions.resetNewRun({ prompt: '', profile: null, ...prefill(values.settings, null) })
            // pinned: analytics event name. A rename breaks the dashboards that read it.
            posthog.capture('cloud_agents_new_run_opened')
        },
        loadSettingsSuccess: ({ settings }) => {
            // The modal can open from a link before the team defaults load. Fill the fields that the person did not touch.
            if (values.isNewRunModalOpen && !values.newRunChanged && settings) {
                actions.resetNewRun({ prompt: '', profile: null, ...prefill(settings, null) })
            }
        },
        selectProfile: ({ profileId }) => {
            const profile = values.profiles?.find((candidate) => candidate.name === profileId) ?? null
            actions.setNewRunValues({ profile: profile?.name ?? null, ...prefill(profile, values.settings) })
        },
        closeNewRunModal: () => {
            const { searchParams, hashParams, location } = router.values
            if (searchParams[NEW_RUN_SEARCH_PARAM]) {
                const { [NEW_RUN_SEARCH_PARAM]: _, ...rest } = searchParams
                router.actions.replace(location.pathname, rest, hashParams)
            }
        },
    })),
    urlToAction(({ actions, values }) => ({
        [urls.cloudAgents()]: (_, searchParams) => {
            if (searchParams[NEW_RUN_SEARCH_PARAM] && !values.isNewRunModalOpen) {
                actions.openNewRunModal()
            }
        },
    })),
])
