import { MakeLogicType, actions, afterMount, connect, kea, listeners, path, reducers } from 'kea'
import { loaders } from 'kea-loaders'

import { lemonToast } from '@posthog/lemon-ui'

import { projectLogic } from 'scenes/projectLogic'

import { cloudAgentsProfilesDestroy, cloudAgentsProfilesList } from '../generated/api'
import type { ProfileApi } from '../generated/api.schemas'

const PROFILES_PAGE_SIZE = 200

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface cloudAgentProfilesLogicValues {
    currentProjectId: number | null // projectLogic
    deletingProfileId: string | null
    profiles: ProfileApi[] | null
    profilesLoadFailed: boolean
    profilesLoading: boolean
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface cloudAgentProfilesLogicActions {
    deleteProfile: (profile: ProfileApi) => {
        profile: ProfileApi
    }
    deleteProfileDone: () => {
        value: true
    }
    loadProfiles: () => any
    loadProfilesFailure: (
        error: string,
        errorObject?: any
    ) => {
        error: string
        errorObject?: any
    }
    loadProfilesSuccess: (
        profiles: ProfileApi[],
        payload?: any
    ) => {
        profiles: ProfileApi[]
        payload?: any
    }
}

export type cloudAgentProfilesLogicType = MakeLogicType<cloudAgentProfilesLogicValues, cloudAgentProfilesLogicActions>

export const cloudAgentProfilesLogic = kea<cloudAgentProfilesLogicType>([
    path(['products', 'cloud_agents', 'frontend', 'logics', 'cloudAgentProfilesLogic']),
    connect(() => ({ values: [projectLogic, ['currentProjectId']] })),
    actions({
        deleteProfile: (profile: ProfileApi) => ({ profile }),
        deleteProfileDone: true,
    }),
    loaders(({ values }) => ({
        profiles: [
            null as ProfileApi[] | null,
            {
                loadProfiles: async (): Promise<ProfileApi[]> => {
                    const response = await cloudAgentsProfilesList(String(values.currentProjectId), {
                        limit: PROFILES_PAGE_SIZE,
                    })
                    return response.results
                },
            },
        ],
    })),
    reducers({
        profilesLoadFailed: [false, { loadProfiles: () => false, loadProfilesFailure: () => true }],
        deletingProfileId: [
            null as string | null,
            { deleteProfile: (_, { profile }) => profile.id, deleteProfileDone: () => null },
        ],
    }),
    listeners(({ actions, values }) => ({
        deleteProfile: async ({ profile }) => {
            try {
                await cloudAgentsProfilesDestroy(String(values.currentProjectId), profile.id)
                lemonToast.success(`Deleted the profile "${profile.name}"`)
                actions.loadProfiles()
            } catch {
                lemonToast.error(`Could not delete the profile "${profile.name}". Try again.`)
            } finally {
                actions.deleteProfileDone()
            }
        },
    })),
    afterMount(({ actions }) => {
        actions.loadProfiles()
    }),
])
