import { MakeLogicType, actions, afterMount, connect, kea, listeners, path, reducers } from 'kea'
import { forms } from 'kea-forms'
import type { DeepPartial, DeepPartialMap, FieldName, ValidationErrorType } from 'kea-forms'
import { loaders } from 'kea-loaders'
import posthog from 'posthog-js'

import { lemonToast } from '@posthog/lemon-ui'

import { projectLogic } from 'scenes/projectLogic'

import {
    cloudAgentsWebhookEndpointsCreate,
    cloudAgentsWebhookEndpointsDeliveriesList,
    cloudAgentsWebhookEndpointsDestroy,
    cloudAgentsWebhookEndpointsList,
    cloudAgentsWebhookEndpointsPartialUpdate,
    cloudAgentsWebhookEndpointsRotateSecretCreate,
    cloudAgentsWebhookEndpointsSecretCreate,
    cloudAgentsWebhookEndpointsTestCreate,
} from '../generated/api'
import type { WebhookDeliveryApi, WebhookEndpointApi, WebhookEventEnumApi } from '../generated/api.schemas'
import type { CloudAgentSettingsApi } from '../generated/api.schemas'
import { cloudAgentsSettingsLogic } from './cloudAgentsSettingsLogic'

export interface NewWebhookEndpointForm {
    url: string
    event_types: WebhookEventEnumApi[]
}

const ENDPOINTS_PAGE_SIZE = 100

function errorDetail(error: unknown, fallback: string): string {
    return (error as { detail?: string | null } | null)?.detail || fallback
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface cloudAgentsWebhooksLogicValues {
    settings: CloudAgentSettingsApi | null // cloudAgentsSettingsLogic
    currentProjectId: number | null // projectLogic
    busyEndpointIds: string[]
    deliveries: WebhookDeliveryApi[] | null
    deliveriesLoadFailed: boolean
    deliveriesLoading: boolean
    endpoints: WebhookEndpointApi[] | null
    endpointsLoadFailed: boolean
    endpointsLoading: boolean
    isNewEndpointSubmitting: boolean
    isNewEndpointValid: boolean
    newEndpoint: NewWebhookEndpointForm
    newEndpointAllErrors: Record<string, any>
    newEndpointChanged: boolean
    newEndpointErrors: DeepPartialMap<NewWebhookEndpointForm, ValidationErrorType>
    newEndpointHasErrors: boolean
    newEndpointManualErrors: Record<string, any>
    newEndpointTouched: boolean
    newEndpointTouches: Record<string, boolean>
    newEndpointValidationErrors: DeepPartialMap<NewWebhookEndpointForm, ValidationErrorType>
    revealedSecret: string | null
    secretRequestInFlight: boolean
    showNewEndpointErrors: boolean
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface cloudAgentsWebhooksLogicActions {
    loadSettings: () => any // cloudAgentsSettingsLogic
    createSecret: () => {
        value: true
    }
    deleteEndpoint: (endpoint: WebhookEndpointApi) => {
        endpoint: WebhookEndpointApi
    }
    dismissSecret: () => {
        value: true
    }
    endpointRequestDone: (endpointId: string) => {
        endpointId: string
    }
    loadDeliveries: () => any
    loadDeliveriesFailure: (
        error: string,
        errorObject?: any
    ) => {
        error: string
        errorObject?: any
    }
    loadDeliveriesSuccess: (
        deliveries: WebhookDeliveryApi[],
        payload?: any
    ) => {
        deliveries: WebhookDeliveryApi[]
        payload?: any
    }
    loadEndpoints: () => any
    loadEndpointsFailure: (
        error: string,
        errorObject?: any
    ) => {
        error: string
        errorObject?: any
    }
    loadEndpointsSuccess: (
        endpoints: WebhookEndpointApi[],
        payload?: any
    ) => {
        endpoints: WebhookEndpointApi[]
        payload?: any
    }
    resetNewEndpoint: (values?: NewWebhookEndpointForm) => {
        values?: NewWebhookEndpointForm
    }
    rotateSecret: () => {
        value: true
    }
    secretRequestDone: (secret: string | null) => {
        secret: string | null
    }
    sendTestEvent: (endpoint: WebhookEndpointApi) => {
        endpoint: WebhookEndpointApi
    }
    setEndpointEnabled: (
        endpoint: WebhookEndpointApi,
        enabled: boolean
    ) => {
        enabled: boolean
        endpoint: WebhookEndpointApi
    }
    setNewEndpointManualErrors: (errors: Record<string, any>) => {
        errors: Record<string, any>
    }
    setNewEndpointValue: (
        key: FieldName,
        value: any
    ) => {
        name: FieldName
        value: any
    }
    setNewEndpointValues: (values: DeepPartial<NewWebhookEndpointForm>) => {
        values: DeepPartial<NewWebhookEndpointForm>
    }
    submitNewEndpoint: () => {
        value: boolean
    }
    submitNewEndpointFailure: (
        error: Error,
        errors: Record<string, any>
    ) => {
        error: Error
        errors: Record<string, any>
    }
    submitNewEndpointRequest: (newEndpoint: NewWebhookEndpointForm) => {
        newEndpoint: NewWebhookEndpointForm
    }
    submitNewEndpointSuccess: (newEndpoint: NewWebhookEndpointForm) => {
        newEndpoint: NewWebhookEndpointForm
    }
    touchNewEndpointField: (key: string) => {
        key: string
    }
}

export type cloudAgentsWebhooksLogicType = MakeLogicType<
    cloudAgentsWebhooksLogicValues,
    cloudAgentsWebhooksLogicActions
>

export const cloudAgentsWebhooksLogic = kea<cloudAgentsWebhooksLogicType>([
    path(['products', 'cloud_agents', 'frontend', 'logics', 'cloudAgentsWebhooksLogic']),
    connect(() => ({
        values: [projectLogic, ['currentProjectId'], cloudAgentsSettingsLogic, ['settings']],
        actions: [cloudAgentsSettingsLogic, ['loadSettings']],
    })),
    actions({
        setEndpointEnabled: (endpoint: WebhookEndpointApi, enabled: boolean) => ({ endpoint, enabled }),
        deleteEndpoint: (endpoint: WebhookEndpointApi) => ({ endpoint }),
        sendTestEvent: (endpoint: WebhookEndpointApi) => ({ endpoint }),
        endpointRequestDone: (endpointId: string) => ({ endpointId }),
        createSecret: true,
        rotateSecret: true,
        secretRequestDone: (secret: string | null) => ({ secret }),
        dismissSecret: true,
    }),
    loaders(({ values }) => ({
        endpoints: [
            null as WebhookEndpointApi[] | null,
            {
                loadEndpoints: async (): Promise<WebhookEndpointApi[]> =>
                    (
                        await cloudAgentsWebhookEndpointsList(String(values.currentProjectId), {
                            limit: ENDPOINTS_PAGE_SIZE,
                        })
                    ).results,
            },
        ],
        deliveries: [
            null as WebhookDeliveryApi[] | null,
            {
                loadDeliveries: async (): Promise<WebhookDeliveryApi[]> =>
                    await cloudAgentsWebhookEndpointsDeliveriesList(String(values.currentProjectId)),
            },
        ],
    })),
    reducers({
        endpointsLoadFailed: [false, { loadEndpoints: () => false, loadEndpointsFailure: () => true }],
        deliveriesLoadFailed: [false, { loadDeliveries: () => false, loadDeliveriesFailure: () => true }],
        // The ID of each endpoint that has a request in flight, so its row controls stay disabled.
        busyEndpointIds: [
            [] as string[],
            {
                setEndpointEnabled: (state, { endpoint }) => [...state, endpoint.id],
                deleteEndpoint: (state, { endpoint }) => [...state, endpoint.id],
                sendTestEvent: (state, { endpoint }) => [...state, endpoint.id],
                endpointRequestDone: (state, { endpointId }) => state.filter((id) => id !== endpointId),
            },
        ],
        secretRequestInFlight: [
            false,
            { createSecret: () => true, rotateSecret: () => true, secretRequestDone: () => false },
        ],
        // The API returns the secret one time, so it lives here until the person closes it.
        revealedSecret: [
            null as string | null,
            { secretRequestDone: (state, { secret }) => secret ?? state, dismissSecret: () => null },
        ],
    }),
    forms(({ actions, values }) => ({
        newEndpoint: {
            defaults: { url: '', event_types: [] } as NewWebhookEndpointForm,
            errors: ({ url }) => ({
                url: !url.trim()
                    ? 'Enter the URL that receives the events'
                    : !/^https:\/\/\S+$/.test(url.trim())
                      ? 'The URL must start with https://'
                      : undefined,
            }),
            submit: async (form) => {
                try {
                    await cloudAgentsWebhookEndpointsCreate(String(values.currentProjectId), {
                        url: form.url.trim(),
                        event_types: form.event_types,
                    })
                } catch (error) {
                    actions.setNewEndpointManualErrors({
                        url: errorDetail(error, 'Could not add the endpoint. Check the URL and try again.'),
                    })
                    throw error
                }
                actions.resetNewEndpoint()
                actions.loadEndpoints()
            },
        },
    })),
    listeners(({ actions, values }) => ({
        setEndpointEnabled: async ({ endpoint, enabled }) => {
            try {
                await cloudAgentsWebhookEndpointsPartialUpdate(String(values.currentProjectId), endpoint.id, {
                    enabled,
                })
                actions.loadEndpoints()
            } catch (error) {
                lemonToast.error(errorDetail(error, 'Could not update the endpoint. Try again.'))
            } finally {
                actions.endpointRequestDone(endpoint.id)
            }
        },
        deleteEndpoint: async ({ endpoint }) => {
            try {
                await cloudAgentsWebhookEndpointsDestroy(String(values.currentProjectId), endpoint.id)
                lemonToast.success('Deleted the endpoint')
                actions.loadEndpoints()
            } catch (error) {
                lemonToast.error(errorDetail(error, 'Could not delete the endpoint. Try again.'))
            } finally {
                actions.endpointRequestDone(endpoint.id)
            }
        },
        sendTestEvent: async ({ endpoint }) => {
            // pinned: analytics event name. A rename breaks the dashboards that read it.
            posthog.capture('cloud_agents_webhook_test_clicked')
            try {
                await cloudAgentsWebhookEndpointsTestCreate(String(values.currentProjectId), endpoint.id)
                lemonToast.success('Sent a test event. It shows in recent deliveries in a few seconds.')
                actions.loadDeliveries()
            } catch (error) {
                lemonToast.error(errorDetail(error, 'Could not send the test event. Try again.'))
            } finally {
                actions.endpointRequestDone(endpoint.id)
            }
        },
        createSecret: async () => {
            try {
                const response = await cloudAgentsWebhookEndpointsSecretCreate(String(values.currentProjectId))
                actions.secretRequestDone(response.secret)
                actions.loadSettings()
            } catch (error) {
                lemonToast.error(errorDetail(error, 'Could not create the signing secret. Try again.'))
                actions.secretRequestDone(null)
            }
        },
        rotateSecret: async () => {
            try {
                const response = await cloudAgentsWebhookEndpointsRotateSecretCreate(String(values.currentProjectId))
                actions.secretRequestDone(response.secret)
                actions.loadSettings()
            } catch (error) {
                lemonToast.error(errorDetail(error, 'Could not rotate the signing secret. Try again.'))
                actions.secretRequestDone(null)
            }
        },
    })),
    afterMount(({ actions }) => {
        actions.loadEndpoints()
        actions.loadDeliveries()
    }),
])
