import { MakeLogicType, actions, afterMount, kea, listeners, path, reducers, selectors } from 'kea'
import { loaders } from 'kea-loaders'
import posthog from 'posthog-js'

import { lemonToast } from '@posthog/lemon-ui'

import {
    usersIntegrationsInferenceCredentialsCreate,
    usersIntegrationsInferenceCredentialsDestroy,
    usersIntegrationsInferenceCredentialsRetrieve,
} from '~/generated/core/api'
import type { InferenceCredentialKindEnumApi, UserInferenceCredentialApi } from '~/generated/core/api.schemas'

import { describeCredentialError } from '../utils/errors'

/** The user segment of the credentials URL. `@me` is the signed-in user. */
const CURRENT_USER = '@me'

type PerKind<T> = Partial<Record<InferenceCredentialKindEnumApi, T>>

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface inferenceCredentialsLogicValues {
    connectErrors: PerKind<string | null>
    connecting: PerKind<boolean>
    credentials: UserInferenceCredentialApi[] | null
    credentialsByKind: PerKind<UserInferenceCredentialApi>
    credentialsLoadFailed: boolean
    credentialsLoading: boolean
    removing: PerKind<boolean>
    secrets: PerKind<string>
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface inferenceCredentialsLogicActions {
    connectCredential: (kind: InferenceCredentialKindEnumApi) => {
        kind: InferenceCredentialKindEnumApi
    }
    connectCredentialDone: (
        kind: InferenceCredentialKindEnumApi,
        error: string | null
    ) => {
        error: string | null
        kind: InferenceCredentialKindEnumApi
    }
    loadCredentials: () => any
    loadCredentialsFailure: (
        error: string,
        errorObject?: any
    ) => {
        error: string
        errorObject?: any
    }
    loadCredentialsSuccess: (
        credentials: UserInferenceCredentialApi[],
        payload?: any
    ) => {
        credentials: UserInferenceCredentialApi[]
        payload?: any
    }
    removeCredential: (kind: InferenceCredentialKindEnumApi) => {
        kind: InferenceCredentialKindEnumApi
    }
    removeCredentialDone: (kind: InferenceCredentialKindEnumApi) => {
        kind: InferenceCredentialKindEnumApi
    }
    setSecret: (
        kind: InferenceCredentialKindEnumApi,
        secret: string
    ) => {
        kind: InferenceCredentialKindEnumApi
        secret: string
    }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface inferenceCredentialsLogicMeta {
    __keaTypeGenInternalSelectorTypes: {
        credentialsByKind: (credentials: UserInferenceCredentialApi[] | null) => PerKind<UserInferenceCredentialApi>
    }
}

export type inferenceCredentialsLogicType = MakeLogicType<
    inferenceCredentialsLogicValues,
    inferenceCredentialsLogicActions,
    Record<string, any>,
    inferenceCredentialsLogicMeta
>

/** The model provider credentials of the signed-in user. Each person connects their own. */
export const inferenceCredentialsLogic = kea<inferenceCredentialsLogicType>([
    path(['products', 'cloud_agents', 'frontend', 'logics', 'inferenceCredentialsLogic']),
    actions({
        setSecret: (kind: InferenceCredentialKindEnumApi, secret: string) => ({ kind, secret }),
        connectCredential: (kind: InferenceCredentialKindEnumApi) => ({ kind }),
        connectCredentialDone: (kind: InferenceCredentialKindEnumApi, error: string | null) => ({ kind, error }),
        removeCredential: (kind: InferenceCredentialKindEnumApi) => ({ kind }),
        removeCredentialDone: (kind: InferenceCredentialKindEnumApi) => ({ kind }),
    }),
    loaders({
        credentials: [
            null as UserInferenceCredentialApi[] | null,
            {
                loadCredentials: async (): Promise<UserInferenceCredentialApi[]> =>
                    (await usersIntegrationsInferenceCredentialsRetrieve(CURRENT_USER)).results,
            },
        ],
    }),
    reducers({
        credentialsLoadFailed: [false, { loadCredentials: () => false, loadCredentialsFailure: () => true }],
        secrets: [
            {} as PerKind<string>,
            {
                setSecret: (state, { kind, secret }) => ({ ...state, [kind]: secret }),
                connectCredentialDone: (state, { kind, error }) => (error ? state : { ...state, [kind]: '' }),
            },
        ],
        connecting: [
            {} as PerKind<boolean>,
            {
                connectCredential: (state, { kind }) => ({ ...state, [kind]: true }),
                connectCredentialDone: (state, { kind }) => ({ ...state, [kind]: false }),
            },
        ],
        connectErrors: [
            {} as PerKind<string | null>,
            {
                connectCredential: (state, { kind }) => ({ ...state, [kind]: null }),
                connectCredentialDone: (state, { kind, error }) => ({ ...state, [kind]: error }),
            },
        ],
        removing: [
            {} as PerKind<boolean>,
            {
                removeCredential: (state, { kind }) => ({ ...state, [kind]: true }),
                removeCredentialDone: (state, { kind }) => ({ ...state, [kind]: false }),
            },
        ],
    }),
    selectors({
        credentialsByKind: [
            (s) => [s.credentials],
            (credentials: UserInferenceCredentialApi[] | null): PerKind<UserInferenceCredentialApi> =>
                Object.fromEntries((credentials ?? []).map((credential) => [credential.kind, credential])),
        ],
    }),
    listeners(({ actions, values }) => ({
        connectCredential: async ({ kind }) => {
            // pinned: analytics event and property names. A rename breaks the dashboards that read them.
            posthog.capture('cloud_agents_credential_connect_clicked', { kind })
            const secret = (values.secrets[kind] ?? '').trim()
            if (!secret) {
                actions.connectCredentialDone(kind, 'Paste the key first.')
                return
            }
            try {
                await usersIntegrationsInferenceCredentialsCreate(CURRENT_USER, { kind, secret })
                actions.connectCredentialDone(kind, null)
                lemonToast.success('Connected your model provider')
                actions.loadCredentials()
            } catch (error) {
                actions.connectCredentialDone(kind, describeCredentialError(error))
            }
        },
        removeCredential: async ({ kind }) => {
            try {
                await usersIntegrationsInferenceCredentialsDestroy(CURRENT_USER, kind)
                lemonToast.success('Removed the credential')
                actions.loadCredentials()
            } catch {
                lemonToast.error('Could not remove the credential. Try again.')
            } finally {
                actions.removeCredentialDone(kind)
            }
        },
    })),
    afterMount(({ actions }) => {
        actions.loadCredentials()
    }),
])
