# Generated by Django 5.2.18 on 2026-10-07 10:27

import django.db.models.manager
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models

import posthog.uuidt
import posthog.helpers.encrypted_fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("posthog", "1394_backfill_secret_tokens_to_psak"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CloudAgentProfile",
            fields=[
                ("repository", models.CharField(blank=True, max_length=255, null=True)),
                ("branch", models.CharField(blank=True, max_length=255, null=True)),
                ("model", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1x2", "1 vCPU, 2 GiB"),
                            ("2x4", "2 vCPU, 4 GiB"),
                            ("2x8", "2 vCPU, 8 GiB"),
                            ("4x8", "4 vCPU, 8 GiB"),
                            ("4x16", "4 vCPU, 16 GiB"),
                            ("8x16", "8 vCPU, 16 GiB"),
                            ("8x32", "8 vCPU, 32 GiB"),
                            ("16x64", "16 vCPU, 64 GiB"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "inference",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("auto", "Auto"),
                            ("own_key", "Own Key"),
                            ("own_subscription", "Own Subscription"),
                            ("posthog", "PostHog"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("instructions", models.TextField(blank=True, null=True)),
                ("create_pr", models.BooleanField(blank=True, null=True)),
                (
                    "pr_mode",
                    models.CharField(
                        blank=True, choices=[("draft", "Draft"), ("ready", "Ready")], max_length=16, null=True
                    ),
                ),
                ("max_duration_minutes", models.PositiveIntegerField(blank=True, null=True)),
                ("max_cost_usd", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                (
                    "id",
                    models.UUIDField(default=posthog.uuidt.uuid7, editable=False, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                ("tags", models.JSONField(blank=True, default=list)),
                ("webhook_url", models.URLField(blank=True, max_length=2000, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="posthog.team",
                    ),
                ),
            ],
            options={
                "default_manager_name": "all_teams",
            },
            managers=[
                ("all_teams", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="CloudAgentRun",
            fields=[
                (
                    "id",
                    models.UUIDField(default=posthog.uuidt.uuid7, editable=False, primary_key=True, serialize=False),
                ),
                (
                    "caller_kind",
                    models.CharField(
                        choices=[("api", "API"), ("app", "App"), ("internal", "Internal")], default="api", max_length=16
                    ),
                ),
                ("caller_product", models.CharField(blank=True, max_length=40, null=True)),
                ("billable", models.BooleanField(default=True)),
                ("task_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("current_task_run_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("agent_sessions", models.JSONField(blank=True, default=list)),
                ("prompt", models.TextField()),
                ("repository", models.CharField(max_length=255)),
                ("branch", models.CharField(blank=True, max_length=255, null=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("idempotency_key", models.CharField(blank=True, max_length=100, null=True)),
                ("request_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("webhook_url", models.URLField(blank=True, max_length=2000, null=True)),
                ("config", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                (
                    "stop_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("done", "Done"),
                            ("cancelled", "Cancelled"),
                            ("error", "Error"),
                            ("timeout", "Timeout"),
                            ("budget_exceeded", "Budget Exceeded"),
                            ("usage_limit", "Usage Limit"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("error", models.TextField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("pr_url", models.URLField(blank=True, max_length=2000, null=True)),
                ("pr_urls", models.JSONField(blank=True, default=list)),
                ("summary", models.TextField(blank=True, null=True)),
                ("compute_usd", models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ("inference_usd", models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ("vcpu_seconds", models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ("gib_seconds", models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                (
                    "billing_mode",
                    models.CharField(
                        choices=[("billed", "Billed"), ("unbilled", "Unbilled")], default="billed", max_length=16
                    ),
                ),
                (
                    "inference_billing",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("posthog", "PostHog"),
                            ("own_key", "Own Key"),
                            ("own_subscription", "Own Subscription"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("cost_final", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="cloud_agents.cloudagentprofile",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="posthog.team",
                    ),
                ),
            ],
            options={
                "default_manager_name": "all_teams",
            },
            managers=[
                ("all_teams", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="CloudAgentsWebhookEndpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(default=posthog.uuidt.uuid7, editable=False, primary_key=True, serialize=False),
                ),
                ("url", models.URLField(max_length=2000)),
                ("enabled", models.BooleanField(default=True)),
                ("event_types", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="posthog.team",
                    ),
                ),
            ],
            options={
                "default_manager_name": "all_teams",
            },
            managers=[
                ("all_teams", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="CloudAgentsWebhookDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(default=posthog.uuidt.uuid7, editable=False, primary_key=True, serialize=False),
                ),
                ("url", models.URLField(max_length=2000)),
                ("run_id", models.UUIDField()),
                ("event_type", models.CharField(max_length=32)),
                ("event_id", models.UUIDField()),
                ("payload", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("gave_up", "Gave Up"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_status_code", models.PositiveIntegerField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, max_length=100, null=True)),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "team",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="posthog.team",
                    ),
                ),
                (
                    "endpoint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="cloud_agents.cloudagentswebhookendpoint",
                    ),
                ),
            ],
            options={
                "default_manager_name": "all_teams",
            },
            managers=[
                ("all_teams", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="TeamCloudAgentsConfig",
            fields=[
                ("repository", models.CharField(blank=True, max_length=255, null=True)),
                ("branch", models.CharField(blank=True, max_length=255, null=True)),
                ("model", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1x2", "1 vCPU, 2 GiB"),
                            ("2x4", "2 vCPU, 4 GiB"),
                            ("2x8", "2 vCPU, 8 GiB"),
                            ("4x8", "4 vCPU, 8 GiB"),
                            ("4x16", "4 vCPU, 16 GiB"),
                            ("8x16", "8 vCPU, 16 GiB"),
                            ("8x32", "8 vCPU, 32 GiB"),
                            ("16x64", "16 vCPU, 64 GiB"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "inference",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("auto", "Auto"),
                            ("own_key", "Own Key"),
                            ("own_subscription", "Own Subscription"),
                            ("posthog", "PostHog"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("instructions", models.TextField(blank=True, null=True)),
                ("create_pr", models.BooleanField(blank=True, null=True)),
                (
                    "pr_mode",
                    models.CharField(
                        blank=True, choices=[("draft", "Draft"), ("ready", "Ready")], max_length=16, null=True
                    ),
                ),
                ("max_duration_minutes", models.PositiveIntegerField(blank=True, null=True)),
                ("max_cost_usd", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                (
                    "team",
                    models.OneToOneField(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="posthog.team",
                    ),
                ),
                ("max_concurrent_runs", models.PositiveIntegerField(blank=True, null=True)),
                ("create_rate_per_hour", models.PositiveIntegerField(blank=True, null=True)),
                ("webhook_secret", posthog.helpers.encrypted_fields.EncryptedTextField(blank=True, null=True)),
                ("webhook_secret_created_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "default_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="cloud_agents.cloudagentprofile",
                    ),
                ),
            ],
            options={
                "default_manager_name": "all_teams",
            },
            managers=[
                ("all_teams", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name="cloudagentprofile",
            constraint=models.UniqueConstraint(
                models.F("team"),
                django.db.models.functions.text.Lower("name"),
                condition=models.Q(("deleted", False)),
                name="cloud_agents_profile_unique_name",
            ),
        ),
        migrations.AddIndex(
            model_name="cloudagentrun",
            index=models.Index(fields=["team", "-created_at"], name="cloud_agents_run_team_created"),
        ),
        migrations.AddIndex(
            model_name="cloudagentrun",
            index=models.Index(fields=["team", "status"], name="cloud_agents_run_team_status"),
        ),
        migrations.AddIndex(
            model_name="cloudagentrun",
            index=models.Index(
                condition=models.Q(("status__in", ["queued", "running"])),
                fields=["last_synced_at"],
                name="cloud_agents_run_active_sync",
            ),
        ),
        migrations.AddIndex(
            model_name="cloudagentrun",
            index=models.Index(
                condition=models.Q(("cost_final", False)),
                fields=["completed_at"],
                name="cloud_agents_run_cost_pending",
            ),
        ),
        migrations.AddConstraint(
            model_name="cloudagentrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key__isnull", False)),
                fields=("team", "idempotency_key"),
                name="cloud_agents_run_unique_idempotency_key",
            ),
        ),
        migrations.AddIndex(
            model_name="cloudagentswebhookdelivery",
            index=models.Index(fields=["team", "-created_at"], name="cloud_agents_delivery_created"),
        ),
        migrations.AddIndex(
            model_name="cloudagentswebhookdelivery",
            index=models.Index(
                condition=models.Q(("status", "pending")),
                fields=["next_attempt_at"],
                name="cloud_agents_delivery_due",
            ),
        ),
    ]
